dist: trusty

sudo: false

language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION="4.1.*"
  - SYMFONY_VERSION="4.2.*"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION="4.2.*"

before_install:
  - phpenv config-rm xdebug.ini

install:
  - >
    composer require
    symfony/config:$SYMFONY_VERSION
    symfony/console:$SYMFONY_VERSION
    symfony/dependency-injection:$SYMFONY_VERSION
    symfony/framework-bundle:$SYMFONY_VERSION
    symfony/http-kernel:$SYMFONY_VERSION
    symfony/workflow:$SYMFONY_VERSION
    symfony/yaml:$SYMFONY_VERSION
    --no-update
  - composer install --no-interaction --profile --no-progress

script:
  - php ./vendor/bin/phpunit
